name: Build and Release LaTeX document

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf-output
          path: main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf-output
          path: ./output

      - name: Rename for Release
        run: mv ./output/main.pdf ./output/cumcm.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./output/cumcm.pdf
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: "Automated release of ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
